dbg = require "debugger"
util = require("lua2bash-util")

local function max(x, y)
    if x > y then return x
    else return y end
end

local bdsl = {}

local mtab = {}
local dslObjects = {}

mtab.__call = function(callee, arg)
    return callee:render(arg)
end
mtab.__concat = function(l, r)
    assert(l and r, "Arguments must not be nil")
    assert((getmetatable(l) == mtab or type(l) == "string") and
            (getmetatable(r) == mtab or type(r) == "string"),
        "Arguments must have been generated by bash EDSL functions\n" ..
            "type left: " .. type(l) .. " type right: " .. type(r))
    if type(l) == "string" then
        l = dslObjects.String(l)
    end
    if type(r) == "string" then
        r = dslObjects.String(r)
    end
end

local function bDslConcat(l, r)
    assert(getmetatable(l) == bashDslMtab and
               getmetatable(r) == bashDslMtab,
           "Arguments must have been generated by bash EDSL functions\n" ..
               "type left: " .. type(l) .. " type right: " .. type(r))
    return makeBdsl({}, "", "", l() .. r(), max(l.nesting, r.nesting))
end

function dslObjects.Concat(left, right)
    local t = {}
    t._left = left
    t._right = right
    function t:render()
        return self:getLeft():render() .. self:getRight():render()
    end
    function t:shallowLift(n)
        self:getLeft():shallowLift(n)
        self:getRight():shallowLift(n)
        return self
    end
    function t:deepLift(n)
        self:getLeft():deepLift(n)
        self:getRight():deepLift(n)
        return self
    end
    function t:getLeft() return self._left end
    function t:getRight() return self._right end
    function t:getQuotingIndex()
        return max(self:getLeft():getQuotingIndex(),
                   self:getRight():getQuotingIndex())
    end
    setmetatable(t, mtab)
    return t
end

function dslObjects.Base(activeChars, begin, ending, dslobj)
    local t = {}
    local temp = {}
    for _, v in pairs(activeChars) do
        temp[v] = true
    end
    t._activeChars = temp
    t._begin = begin
    t._quotingIndex = dslobj:getQuotingIndex() + 1
    t._dependentQuoting = true
    if type(dslobj) == "string" then
        t._subtree = dslObjects.String(dslobj)
    else
        t._subtree = dslobj
    end
    t._end = ending
    function t:shallowLift(n)
        self._quotingIndex = self._quotingIndex + n
        return self
    end
    function t:deepLift(n)
        self:shallowLift(n)
        self:getSubtree():deepLift(n)
        return self
    end
    function t:noDependentQuoting()
        self._dependentQuoting = false
        return self
    end
    --
    function t:getActiveChars() return self._activeChars end
    function t:getBegin() return self._begin end
    function t:getEnd() return self._end end
    function t:getSubtree() return self._subtree end
    function t:getQuotingIndex() return self._quotingIndex end
    function t:render()
        local result, middle = "", self:getSubtree():render()
        local ac, begin, ending = self:getActiveChars(), self:getBegin(), self:getEnd()
        local nesting, repCount = t:getQuotingIndex(), nil
        if nesting > 0 then
            repCount = 2 ^ (nesting - 1) - 1
        else
            repCount = 0
        end
        for c in begin:gmatch(".") do
            if ac[c] then result = result .. string.rep("\\", repCount) .. c
            else result = result .. c end
        end
        result = result .. middle
        for c in ending:gmatch(".") do
            if ac[c] then result = result .. string.rep("\\", repCount) .. c
            else result = result .. c end
        end
        return result
    end
    setmetatable(t, mtab)
    return t
end

function dslObject.String(str)
    local t = {}
    t._content = str
    function t:shallowLift(n) return self end
    function t:deepLift(n) return self end
    --
    function t:getQuotingIndex() return 0 end
    function t:getSubtree() return nil end
    function t:render() return self._content end
    setmetatable(t, mtab)
    return t
end

function dslObject.Eval(dslobj)
    local t
    t._subtree = dslobj
    t._evalCount = dslobj:getQuotingIndex() - 1
    function t:shallowLift(n) return self end
    function t:deepLift(n)
        t:getSubtree():deepLift(n)
        return self
    end
    --
    function t:evalLift(n)
        self._evalCount = self._evalCount + n
        return self
    end
    --
    function t:getSubtree() return self._subtree end
    function t:getQuotingIndex() return self:getSubtree():getQuotingIndex() end
    function t:getEvalCount() return self._evalCount end
    function t:render()
        local repCount = self:getQuotingIndex() - 1
        if t:getEvalCount() ~= repCount then
            repCount = t:getEvalCount()
        end
        local rest = self:getSubtree():render()
        return string.rep("eval ", repCount) .. rest
    end
    setmetatable(t, mtab)
    return t
end

local function bDslString(v)
    return dslObjects.String(str)
end

local function bDslParentheses(v)
    return dslobjects.Base({"(", ")"}, "(", ")", str)
end

-- does not require more evals for itself
local function bDslParenthesesNoNest(str)
    return dslobjects.Base({"(", ")"}, "(", ")", str)
end

local function bDslParamExpansion(str)
    return dslobjects.Base({"$"}, "${", "}", str )
end

local function bDslSingleQuotes(str)
    return dslobjects.Base({"'"}, "'", "'", str)
end

local function bDslArithExpansion(str)
    return dslobjects.Base({"$", "(", ")"}, "$((", "))", str)
end

local function bDslDoubleQuotes(str)
    return dslobjects.Base({[["]]}, "\"", "\"", str)
end

local function bDslCommandExpansionTicks(str)
    return dslobjects.Base({"`"}, "`", "`", str)
end

local function bDslCommandExpansionParen(str)
    return dslobjects.Base({"$", "(", ")"}, "$(", ")", str)
end

local function bDslBraceExpansion(str)
    return dslobjects.Base({"{", "}"}, "{", "}", str)
end

local function bDslProcessExpansionIn(str)
    return dslobjects.Base({"<", "(", ")"}, "<(", ")", str)
end

local function bDslProcessExpansionOut(str)
    return dslobjects.Base({">", ")", "("}, ">(", ")", str)
end

bDsl.a = bDslAll
bDsl.w = bDslWord
bDsl.eval = bDslEval
bDsl.string = bDslString
bDsl.paramExpansion = bDslParamExpansion
bDsl.singleQuotes = bDslSingleQuotes
bDsl.doubleQuotes = bDslDoubleQuotes
bDsl.processExpansionIn = bDslProcessExpansionIn
bDsl.processExpansionOut = bDslProcessExpansionOut
bDsl.cmdExpansionParen = bDslCommandExpansionParen
bDsl.cmdExpansionTicks = bDslCommandExpansionTicks
bDsl.arithExpansion = bDslArithExpansion
bDsl.braceExpansion = bDslBraceExpansion
bDsl.parentheses = bDslParentheses

return bDsl
